### ISSUE TITLE
Breakage when POSTGRES_DB is provided (and different from username) but POSTGRES_INITDB_ARGS isn't 

### ISSUE THREAD

**Issue by lowne** [pgautoupgrade/docker-pgautoupgrade#20] opened 2024-01-23 12:23 UTC
[This](https://github.com/pgautoupgrade/docker-pgautoupgrade/blob/430eb9290dd9aeed421ffeefdb2502b2bec28477/docker-entrypoint.sh#L491) and following lines need to specify dbname as the last argument, because (from [here](https://www.postgresql.org/docs/current/app-postgres.html))

> **database**
> Specifies the name of the database to be accessed. This must be the last argument on the command line. If it is omitted it defaults to the user name.

So, something like:
```bash
COLLATE=$(echo 'SHOW LC_COLLATE' | "${OLDPATH}/bin/postgres" --single -D "${OLD}" "${POSTGRES_DB}" | grep 'lc_collate = "' | cut -d '"' -f 2)
```

**Comment by justinclift** [comment] 2024-01-23 23:58
Ahhh.  Interesting.

Want to through together a PR that fixes it? :smile:

**Comment by jjb** [comment] 2024-03-15 22:13
with https://github.com/pgautoupgrade/docker-pgautoupgrade/pull/23 and the below compose config i still get 

```
initdb: error: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
initdb: hint: If you want to create a new database system, either remove or empty the directory "/var/lib/postgresql/data/pgdata" or run initdb with an argument other than "/var/lib/postgresql/data/pgdata".
```

```yaml
  postgres:
    image: 'pgautoupgrade/pgautoupgrade:16-alpine'
    environment:
      POSTGRES_USER: 'redacted'
      POSTGRES_PASSWORD: 'redacted'
      POSTGRES_DB: 'redacted'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432'
```

**Comment by jjb** [comment] 2024-03-15 22:16
it might be the locale problem

at least on debian, switching from one image to another with the updated locale situation isn't possible with in-place upgrade (sometimes, always?) - need to do dump and restore or logical replication

**Comment by justinclift** [comment] 2024-03-15 22:25
Hmmm, at first glance I wouldn't think the locale problem would get it to misunderstand the directory it's trying to initdb into.

That being said, it's possible some non-obvious locale related aspect really is throwing it off after all. :frowning:

Don't suppose you can put together a minimal reproducer, so I can trigger the problem here on my dev system and figure out a good solution? :smile:

**Comment by justinclift** [comment] 2024-03-15 22:28
Ahhh, looks like you're investigating it on your systems instead.  I'll put this aside for now then as it's super likely you'll be able to figure it out with that step-by-step approach.

**Comment by jjb** [comment] 2024-03-15 22:29
>  I wouldn't think the locale problem would get it to misunderstand the directory it's trying to initdb into

was thinking more like, maybe some previous step silently failed (maybe not possible)

**Comment by justinclift** [comment] 2024-03-15 22:34
Yeah, might be the case.  If that does turn out to be it, then that'll be another thing we'll need to add checks for. :smile:

**Comment by jjb** [comment] 2024-03-16 22:20
@lowne your fix is now in main 🎉 thanks! https://github.com/pgautoupgrade/docker-pgautoupgrade/commit/ba99db1a6398932999146059d90c5be23bb0375e

**Comment by justinclift** [comment] 2024-03-16 23:35
Awesome.  Closing this issue too, as it's been taken care of.  Thanks heaps @lowne and @jjb. :smile:

**Closed by justinclift** 2024-03-16 23:35 UTC
